### ISSUE TITLE
Adjust the respawn penalty according to the gear

### ISSUE THREAD

**Issue by Lux0r87** [Lux0r87/TacticalTeamCombat#90]
The respawn penalty should depend on the value of the victim's gear.
#### Notes
- [ ] Every player has a custom malus, depending on the number of team kills:
- start malus = 5%
- increase the malus by 5% after every team kill
- [ ] The team killer must pay a penalty to the victim:
- amount = [gearValue \* malus] BTC
- minimum: 500 BTC
- maximum: the balance of the team killer (all his money)
- [ ] The victim receives a compensation from the team killer.
- value of compensation = value of penalty

**Comment by ghost** [comment]
Calculating the penalty based on gear is to time-consuming
